<?$arServices = array(
	'thematics' => array(
		'NAME' => GetMessage('SERVICE_PREPARE_DATA'),
		'MODULE_ID' => 'fileman',
		'STAGES' => array(
			'check.php',
			'download.php',
			'clear.php',
			'unzip.php',
		),
	),
	'main' => array(
		'NAME' => GetMessage('SERVICE_MAIN_SETTINGS'),
		'STAGES' => array(
			'public.php',
			'template.php',
			'theme.php',
			'menu.php',
			'settings.php',
		),
	),
	'iblock' => array(
		'NAME' => GetMessage('SERVICE_IBLOCK_DEMO_DATA'),
		"STAGES" => Array(
			"types.php",
			"banner_types.php",
			"vacancy.php",
			"licenses.php",
			"regions.php",
			"faq.php",
			"megamenu.php",
			"docs.php",
			"adv_content.php",
			"banners_inner.php",
			"tizers.php",
			"shops.php",
			"company.php",
			"banners_float.php",
			"cross_sales.php",
			"marketings.php",
			"staff.php",
			"landing.php",
			"search.php",
			"add_review.php",
			"services.php",
			"projects.php",
			"stock.php",
			"partners.php",
			"catalog_part1.php",
			"catalog_part2.php",
			"catalog_part3.php",
			"catalog_part4.php",
			"catalog_part5.php",
			"banners.php",
			"news.php",
			"sku.php",
			"catalog_info.php",
			"articles.php",
			"brands.php",
			"links.php",
		),
	),
	'form' => array(
		'NAME' => GetMessage('SERVICE_FORM_DEMO_DATA'),
		'STAGES' => array(
			'ask.php',
			'ask_staff.php',
			'callback.php',
			'cheaper.php',
			'feedback.php',
			'one_click_buy.php',
			'projects.php',
			'resume.php',
			'review.php',
			'toorder.php',
			'services.php',
			'send_gift.php',
			'sms.php',
			'errors_updates.php',
		)
	),
	'sale' => array(
		'NAME' => GetMessage('SERVICE_SALE_DEMO_DATA'),
		'STAGES' => array(
			'locations.php',
			'step1.php',
			'step2.php',
			'step3.php'
		),
	),
	'forum' => array(
		'NAME' => GetMessage('SERVICE_FORUM')
	),
	// 'search' => array(
	// 	'NAME' => GetMessage('SERVICE_SEARCH'),
	// 	'STAGES' => array(
	// 		'search.php',
	// 	),
	// ),
);?>